name: Build Docker Image

on:
  push:
    branches: [ main ] # or your desired branch
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: kubernetes-runner-set

    steps:
      # Step 1: Checkout code
      - name: Checkout source
        uses: actions/checkout@v4

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # # Step 3: Log in to DockerHub (optional)
      # - name: Log in to DockerHub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 4: Build and optionally push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false # Set to true if you want to push the image to DockerHub
          tags: your-dockerhub-username/your-image-name:latest
