name: Docker Shell Commands

on:
  push:
    branches: [ main ]

jobs:
  docker-cli:
    runs-on: kubernetes-runner-set
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker CLI Commands
        run: |
          docker version
          docker info
          docker build -t local-image:test .
          docker run --rm local-image:test
