# .github/workflows/test-org-runner.yml
name: Test Org Runner

on: [push]

jobs:
  test:
    runs-on: 
      - self-hosted
      - pgr-devops-k8s-runner
      - arc-runner-set 
      
    steps:
      - run: echo "✅ Running on GitHub Org-level Kubernetes Runner! test2"
